name: CI-CD Elastic beanstalk_AWS

env:
 EB_S3_PACKAGE_BUCKET_NAME: "dior-app-pythonpackages"
 EB_APPLICATION_NAME      : "My_pytnon_app"
 EB_ENVIRONMENT_NAME      : "Python-env"
 DEPLOY_PACKAGE_NAME      : "python_app_${{ github.sha }}.zip"
 AWS-REGION_NAME          : "us-east-1"

on:
  
  push:
    branches: 
      - main 
jobs:
  my_ci_part1:
    runs-on: ubuntu-latest

    steps:
     - name: Git clone repository
       uses: actions/checkout@v2
       
       
     - name: Create zip deployment package
       run : zip -r $ {{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git* 
         

      

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
